const Permission = {
    // SaleService
    "CREATE_SALE": "CREATE_SALE",
    "GET_SALE_ITEMS": "GET_SALE_ITEMS",
    "GET_SALES": "GET_SALES",

    // UserService
    "GET_PROFILE": "GET_PROFILE",
    "EDIT_EMAIL": "EDIT_EMAIL",
    "EDIT_PASSWORD": "EDIT_PASSWORD",
    "CONFIRM_USER_ACTION": "CONFIRM_USER_ACTION",
    "GET_ALL_USERS": "GET_ALL_USERS",
    "CHANGE_STATUS_VL": "CHANGE_STATUS_VL",
    "CHANGE_STATUS": "CHANGE_STATUS",

    // Admin
    "ALL_PERMISSIONS": "ALL_PERMISSIONS",
    "CREATE_ITEM_INFO": "CREATE_ITEM_INFO",


}

module.exports = Permission
